#!/usr/bin/env python3

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Simple script to accept all invitations on GitHub.

It takes GitHub access token as single parameter.
"""

import sys

import requests

TIMEOUT = 60


def main() -> None:
    headers = {
        "Content-Type": "application/json",
        "Authorization": f"token {sys.argv[1]}",
    }

    url = "https://api.github.com/user/memberships/orgs"
    accept_url = "https://api.github.com/user/memberships/orgs/{}"

    orgs = requests.get(
        url,
        headers=headers,
        timeout=TIMEOUT,
    )
    orgs.raise_for_status()

    for org in orgs.json():
        if org["state"] == "pending":
            name = org["organization"]["login"]
            print(f"Accepting org {name}")  # noqa: T201
            response = requests.patch(
                accept_url.format(name),
                '{"state":"active"}',
                headers=headers,
                timeout=TIMEOUT,
            )
            response.raise_for_status()

    url = "https://api.github.com/user/repository_invitations"

    invitations = requests.get(
        url,
        headers=headers,
        timeout=TIMEOUT,
    )
    invitations.raise_for_status()
    for invitation in invitations.json():
        print("Accepting {}".format(invitation["repository"]["html_url"]))  # noqa: T201
        response = requests.patch(
            "{}/{}".format(url, invitation["id"]),
            headers=headers,
            timeout=TIMEOUT,
        )
        response.raise_for_status()


if __name__ == "__main__":
    main()
