#!/bin/sh

# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Renerates .po files used for translating Weblate

# Exit on failure
set -e

export CI_DATABASE=postgresql
export DJANGO_SETTINGS_MODULE=wllegal.settings_test

# Lock Weblate
wlc lock

# Push changes from Weblate to GitHub
wlc push

# Update Weblate remote
git remote update weblate

# Pull changes from GitHub
git rebase --onto weblate/main

# Cleanup locale dirs
find wllegal/locale \( -name '*.mo' -o -name '*~' \) -delete
find wllegal/locale -type d -empty -delete

# Update po files itself
weblate makemessages --keep-pot -a -i 'data/*' -i 'docs/*' -i 'examples/*' -i 'build/*'

# Fix Report-Msgid-Bugs-To as it gets removed
sed \
    -i \
    -e 's@"Report-Msgid-Bugs-To:.*@"Report-Msgid-Bugs-To: https://github.com/WeblateOrg/wllegal/issues\\n"@' \
    -e 's/"Project-Id-Version:.*/"Project-Id-Version: Hosted Weblate Legal\\n"/' \
    wllegal/locale/*/*/*.po wllegal/locale/*.pot

# Commit changes
git add wllegal/locale/*/*/*.po
git add wllegal/locale/*.pot

git commit -m "i18n: Update PO files"

# Push changes
git push

# Unlock Weblate
wlc unlock
